standards_lab/standards_lab/urls.py
# from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include("ui.urls", namespace="ui"), name="ui"),
    #    path("admin/", admin.site.urls),
]

standards_lab/ui/urls.py
from django.urls import path

import ui.views
from ui.apps import UiConfig

app_name = UiConfig.name

urlpatterns = [
    path("", ui.views.Home.as_view(), name="home"),
    path("p/<slug:project_name>", ui.views.ProjectView.as_view(), name="project"),
    path(
        "p/<slug:project_name>/cove-results",
        ui.views.CoveResults.as_view(),
        name="cove-results",
    ),
    path("about", ui.views.About.as_view(template_name="about.html"), name="about"),
    path("sysadmin", ui.views.SysAdmin.as_view(), name="sysadmin"),
    path("sysadmin/login", ui.views.SysAdminLogIn.as_view(), name="sysadmin_login"),
    path("sysadmin/logout", ui.views.SysAdminLogOut.as_view(), name="sysadmin_logout"),
    path("sysadmin/p", ui.views.SysAdminProjects.as_view(), name="sysadmin_projects"),
]

standards_lab/urls.py
# from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include("ui.urls", namespace="ui"), name="ui"),
    path("api/", include("api.urls", namespace="api"), name="api"),
    #    path("admin/", admin.site.urls),
]

standards_lab/ui/views.py
import os
import subprocess
import processor.cove
from django.conf import settings
from django.http import Http404
from django.template.loader import render_to_string
from django.views.generic import TemplateView
from utils.project import get_project_config, create_new_project, delete_project
from django.shortcuts import render, redirect
from django.views import View


class Home(TemplateView):
    template_name = "home.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["projects"] = os.listdir(settings.ROOT_PROJECTS_DIR)
        return context


class About(TemplateView):
    template_name = "about.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # Not critical if this fails e.g. git not installed
        try:
            context["git_rev"] = subprocess.check_output(
                ["git show --format=format:%h  --no-patch"], shell=True
            ).decode()
        except Exception:
            pass

        return context


class ProjectView(TemplateView):
    template_name = "project.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        try:
            context["project"] = get_project_config(
                self.kwargs["project_name"], json_format=True
            )
            return context
        except FileNotFoundError:
            # Create new project
            if self.request.GET.get("new"):
                created_by_me, context["project"] = create_new_project(
                    self.kwargs["project_name"], json_format=True
                )

                if created_by_me:
                    # We created this project so add it to our session's project's owned array
                    try:
                        projects_owned = self.request.session["projects_owned"]
                        projects_owned.append(self.kwargs["project_name"])
                        self.request.session["projects_owned"] = projects_owned
                    except KeyError:
                        self.request.session["projects_owned"] = [
                            self.kwargs["project_name"]
                        ]

                return context

        raise Http404


class CoveResults(TemplateView):
    template_name = "cove_results.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        try:
            context["project"] = get_project_config(self.kwargs["project_name"])
        except FileNotFoundError:
            return Http404

        # Render the lib-cove-web results snippets
        context["cove_results_pages"] = []
        cove = processor.cove.monitor(context["project"])

        try:

            for file_result in cove:
                snippet_context = cove[file_result]["result"]["context"]
                snippet_context["request"] = {
                    "current_app_base_template": "cove_results_snippet_base.html"
                }

                context["cove_results_pages"].append(
                    {
                        "html": render_to_string(
                            "cove_results_snippet.html", snippet_context
                        ),
                        "file_name": file_result,
                    }
                )

        except KeyError:
            context["error"] = "Results Expired"
        finally:
            return context

        return context


class BaseSysAdmin(View):
    def is_user_sysadmin(self, request):
        # If no password configured, don't allow anyone any access
        if not settings.SYSADMIN_PASSWORD:
            return False

        # Check password
        return request.session.get("sysadminPassword") == settings.SYSADMIN_PASSWORD


class SysAdmin(BaseSysAdmin):
    def get(self, request, *args, **kwargs):
        if not self.is_user_sysadmin(request):
            return redirect("/sysadmin/login")

        return render(request, "sysadmin.html")


class SysAdminLogIn(BaseSysAdmin):
    def get(self, request, *args, **kwargs):
        if self.is_user_sysadmin(request):
            return redirect("ui:sysadmin")

        return render(request, "sysadmin_login.html")

    def post(self, request, *args, **kwargs):
        if self.is_user_sysadmin(request):
            return redirect("ui:sysadmin")

        if request.POST.get("password") == settings.SYSADMIN_PASSWORD:
            request.session["sysadminPassword"] = settings.SYSADMIN_PASSWORD
            return redirect("ui:sysadmin")
        else:
            return redirect("ui:sysadmin_login")


class SysAdminLogOut(BaseSysAdmin):
    def get(self, request, *args, **kwargs):
        request.session["sysadminPassword"] = None
        return redirect("ui:sysadmin_login")


class SysAdminProjects(BaseSysAdmin):
    def get(self, request, *args, **kwargs):
        if not self.is_user_sysadmin(request):
            return redirect("ui:sysadmin_login")

        return render(
            request,
            "sysadmin_projects.html",
            {"projects": os.listdir(settings.ROOT_PROJECTS_DIR)},
        )

    def post(self, request, *args, **kwargs):
        if not self.is_user_sysadmin(request):
            return redirect("ui:sysadmin_login")

        for project_name in os.listdir(settings.ROOT_PROJECTS_DIR):
            if request.POST.get("project_" + project_name) == "1":
                delete_project(project_name)

        return redirect("ui:sysadmin_projects")

standards_lab/ui/templates/about.html
{% extends "base.html" %}
{% block title %}About |{% endblock %}
{% block content %}
<div class="container mt-3">
  <h1 class="mb-3 text-right">Open Standards Lab</h1>

  {% include "about_top.html" %}

  <div class="card mb-4">
    <div class="card-body">
      <h5 class="card-title">Who?</h5>
      <p>Built by <a href="http://opendataservices.coop/">Open Data Services Co-operative</a> with funding from the <a href="https://theodi.org/">ODI (Open Data Institute)</a>.</p>
    </div>
  </div>

  <div class="card mb-4">
    <div class="card-body">
      <h5 class="card-title">Technical</h5>
      <p>Git revision: <a href="https://github.com/OpenDataServices/standards-lab/tree/{{ git_rev }}">{{ git_rev }}</a></p>
    </div>
  </div>
</div>
{% endblock %}

standards_lab/ui/templates/about_top.html
<div class="card mb-4">
  <div class="card-body">
    <p>Open Standards Lab is a tool to help you to develop JSON schema and improve the quality of open data. You can:</p>
    <ul>
      <li>Upload and edit JSON schema files</li>
      <li>Upload and edit data in multiple formats</li>
      <li>Test data using your schema</li>
    </ul>
    <p>Note: All projects, data and schema is visible to all users.</p>
  </div>
</div>

standards_lab/ui/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">

  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <title>{% block title %}{% endblock %}Open Standards Lab</title>


    <!-- Style -->
    <link rel="stylesheet" href="{%  static 'bootstrap/css/bootstrap.min.css' %}" >
    <link rel="stylesheet" href="{%  static 'theme.css' %}">
    <link rel="stylesheet" href="{%  static 'style.css' %}">

    <!-- JS-->
    <script src="{% static 'jquery/js/jquery-3.5.1.min.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    {% if debug %}
    <script src="{% static 'vue/js/vue.js' %}"></script>
    {% else %}
    <script src="{% static 'vue/js/vue.min.js' %}"></script>
    {% endif %}

    <script>
      var global = {
        projectRegex : /^[-\w]+$/,
        editMode : {% if EDIT_MODE %}true{% else %}false{% endif %},
      }
    </script>
  </head>

  <body>
    <div class="bg-light">
      <nav class="navbar navbar-expand-lg navbar-light container">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup"
          aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            <a class="nav-link" href="{% url 'ui:home' %}">Home</a>
            <a class="nav-link" href="{% url 'ui:about' %}">About</a>
          </div>
        </div>
      </nav>
    </div>

  {% block content %}
  {% endblock %}

  <footer class="p-4 mt-4 bg-light">
    <div class="container">
      <div class="row">
        <div class="col">
          <p>Open Standards Lab</p>
        </div>
        <div class="col text-right">
          <a href="https://standards-lab.readthedocs.io/">Documentation</a> |
          <a href="https://github.com/OpenDataServices/standards-lab/">GitHub</a>
        </div>
      </div>
     </div>
  </footer>

  </body>
</html>

standards_lab/ui/templates/cove_results.html
{% extends "base.html" %}
{% block title %}Data Test Results | {{ project_name }} |{% endblock %}
{% block content %}
<div class="container mt-2">
  <h1><a href="{% url "ui:project" project.name %}">{{project.name}}</a> - Data Test Results</h1>
  <p><a href="{% url "ui:project" project.name %}">Back to {{project.name}} Project</a></p>

  <div class="card mb-3">
    <div class="card-body">
      <h2 class="card-title">Data Tested</h2>
      <ul>
      {% for cove_result_page in cove_results_pages %}
      <li>
        <a href="#{{cove_result_page.file_name}}">{{cove_result_page.file_name}}</a>
      </li>
      {% endfor %}
      </ul>
    </div>
  </div>

  {% for cove_result_page in cove_results_pages %}
  <div class="card mb-3">
    <div class="card-body">
      <h2 class="card-title" id="{{cove_result_page.file_name}}">{{cove_result_page.file_name}}</h2>
      {{cove_result_page.html}}
    </div>
  </div>
  {% endfor %}

</div>
{% endblock %}

standards_lab/ui/templates/cove_results_snippet.html
{% extends 'explore.html' %}
{% load i18n %}
{% load cove_tags %}


{% block header_button %}
  <div class="row">
    <a href="{% url 'index' %}" class="btn btn-large btn-success">{% trans 'Load New File' %}</a>
  </div>
{% endblock %}

{% block explore_content %}

<div class="container mt-2">
    <div class="row">

        {% if validation_errors %}
              {% for error_json, values in validation_errors %}
                {% with error=error_json|json_decode %}
                  {% cove_modal_errors className="validation-errors-"|concat:forloop.counter modalTitle=error.message errorList=values file_type=file_type full_table=True %}
                {% endwith %}
              {% endfor %}


              <a name="validation-errors" class="anchor"></a>
              <div class="panel panel-danger">
                <div id="validation-panel" class="panel-heading pointer" role="region" aria-expanded="true" >
                  <h4 class="panel-title">
                    {% trans 'Structural Errors' %}
                  </h4>
                </div>
                <div id="validationTable" class="panel-body">
                  {% include "validation_table.html" %}
                </div>
              </div>
        {% else %}
             <div class="panel panel-success">
                <div id="validation-panel" class="panel-heading pointer" role="region">
                  <h4 class="panel-title">
                    {% trans 'Structural Errors' %}
                  </h4>
                </div>
                <div id="validationTable" class="panel-body">
                    <p>{% trans 'There were no structural errors' %}.</p>
                </div>
              </div>
        {% endif %}

    </div>

    <div class="row">

        {% if additional_fields_count %}

              <a name="additional-fields" class="anchor"></a>
              <div class="panel panel-danger">
                <div id="validation-panel" class="panel-heading pointer" role="region" aria-expanded="true" aria-controls="validationTable">
                  <h4 class="panel-title">
                    <span class="glyphicon glyphicon-collapse-up"></span>{% trans 'Additional Fields' %}
                  </h4>
                </div>
                <div id="additionalFieldsTable" class="panel-body">
                  {% include "additional_fields_table_all.html" %}
                </div>
              </div>
        {% else %}
             <div class="panel panel-success">
                <div id="validation-panel" class="panel-heading pointer" role="region" aria-expanded="true" aria-controls="validationTable" >
                  <h4 class="panel-title">
                    <span class="glyphicon glyphicon-collapse-up"></span>{% trans 'Additional Fields' %}
                  </h4>
                </div>
                <div id="additionalFieldsTable" class="collapse in panel-body">
                    <p>{% trans 'There were no additional fields' %}.</p>
                </div>
              </div>
        {% endif %}

    </div>

    {% if additional_open_codelist_values %}
    <div class="row">
      <a name="additional-open-codelist-values" class="anchor"></a>
      <div class="panel panel-warning">
        <div id="additional-open-codelist-values-panel" class="panel-heading pointer" role="region" aria-expanded="true"
          aria-controls="additionalOpenCodelist" data-toggle="collapse" data-target="#additionalOpenCodelist">
          <h4 class="panel-title">
            <span class="our-title"><span
                class="glyphicon glyphicon-collapse-up"></span>{% trans 'Additional Codelist Values' %}</span>
          </h4>
        </div>
        <div class="panel-body">
          {% trans 'Your data contains a number of fields that use an open codelist. You should use values from the codelist whenever possible, but if the codelist does not provide the values you need, you are permitted to add additional values. The values below do not appear in the codelist; you should check that you intended these as additional values.' %}
          <div id="additionalOpenCodelist" class="in">
            {% with additional_codelist_values=additional_open_codelist_values %}
            {% include "additional_codelist_values.html" %}
            {% endwith%}
          </div>
        </div>
      </div>
    </div>
    {% endif %}

</div>
{% endblock explore_content %}


{% block bottomcontent1 %}
{% endblock %}
{% block bottomcontent2 %}
{% endblock %}

standards_lab/ui/templates/cove_results_snippet_base.html
<div>
{% block content %}
{% endblock %}
</div>

standards_lab/ui/templates/home.html
{% extends "base.html" %}
{% block title %}Home |{% endblock %}
{% block content %}
<div class="container mt-3">
  <h1 class="mb-3 text-right">Open Standards Lab</h1>

  {% include "about_top.html" %}

  {% if projects %}
  <div class="card mb-4">
    <div class="card-body">
      <h5 class="card-title">Open An Existing Project</h5>
      <div style="max-height: 20vh; overflow-y: auto;">
        <div style="column-count: 6;">
          <ul>
            {% for project in projects %}
            <li><a href="{% url "ui:project" project %}">{{project}}</a></li>
            {% endfor %}
          </ul>
        </div>
      </div>
    </div>
  </div>
  {% endif %}

  {% if EDIT_MODE %}
  <div class="card">
    <div class="card-body">

    <h5 class="card-title">Create A New Project</h5>

  <div class="form-group">
    <label for="new-project" class="mr-3">Project name</label>
    <input type="text" id="new-project" class="form-control" placeholder="project name" required>
    <small id="accepted-chars-hint">Accepted characters are A-Z, a-z, 0-9 , - and _ </small>
  </div>
  <div class="form-group">
    <a class="btn btn-primary card-link disabled" id="launch-new-project-link" href="#" data-base-url="{% url "ui:project" "__new__" %}?new=true" disabled="disabled">Create</a>
  </div>

  </div>
    </div>
</div>

<script>
  $(document).ready(function(){
    let projectLink = $("#launch-new-project-link");
    let acceptedCharsHint = $("#accepted-chars-hint");

    $("#new-project").on("keyup", function(e){

      if ($(this).val() && global.projectRegex.test($(this).val())){
        acceptedCharsHint.removeClass("text-danger");
        projectLink.removeClass("disabled");
        projectLink.prop({
          disabled: false,
          href: projectLink.data("base-url").replace("__new__", $(this).val()),
        });
      } else {
        acceptedCharsHint.addClass("text-danger");
        projectLink.addClass("disabled").prop({
          href: "#",
          disabled: true
        });
      }
    });

  });
</script>
{% endif %}
{% endblock %}

standards_lab/ui/templates/sysadmin.html
{% extends "sysadmin_base.html" %}
{% block sysadmintitle %}Welcome{% endblock %}
{% block sysadmincontent %}
  Welcome
{% endblock %}

standards_lab/ui/templates/sysadmin_base.html
{% extends "base.html" %}
{% block title %}{% block sysadmintitle %}{% endblock %} | SysAdmin | {% endblock %}
{% block content %}
<div class="container mt-3">
  <h1 class="mb-3 text-right">SysAdmin</h1>

  <div class="text-right mb-5">
    <a class="btn btn-primary" href="{% url 'ui:sysadmin' %}">Home</a>
    <a class="btn btn-primary" href="{% url 'ui:sysadmin_projects' %}">Projects</a>
    <a class="btn btn-primary" href="{% url 'ui:sysadmin_logout' %}">Logout</a>
  </div>

  {% block sysadmincontent %}{% endblock %}
</div>
{% endblock %}

standards_lab/ui/templates/sysadmin_login.html
{% extends "sysadmin_base.html" %}
{% block sysadmintitle %}Login{% endblock %}
{% block sysadmincontent %}

  <h1 class="mb-3 text-right">Login</h1>
    <form method="post" action="#">
        {% csrf_token %}
        <label>
            Password
            <input type="password" name="password">
        </label>
        <input type="submit" value="Login">
    </form>


{% endblock %}

standards_lab/ui/templates/sysadmin_projects.html
{% extends "sysadmin_base.html" %}
{% block sysadmintitle %}Projects{% endblock %}
{% block sysadmincontent %}

  <h1 class="mb-3 text-right">Projects</h1>
    <form action="#" method="post" onsubmit="return confirm('Are you sure you want to delete? There is no undo!');">
        {% csrf_token %}
        <table class="table">
            <Tr>
                <th>Project</th>
            </Tr>
            {% for project in projects %}
                <tr>
                    <td>
                        <label>
                            <input type="checkbox" name="project_{{ project }}" value="1">
                            {{ project }}
                        </label>
                    </td>
                </tr>
            {% endfor %}
        </table>
        <input type="submit" value="Delete">
    </form>

{% endblock %}